### ISSUE TITLE
Support $0.00 products

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-coming-soon#16]
Products that are free do not show the vote count. I see no reason why they shouldn't, though. The way EDD works has probably changed or something since this was written. But I think supporting free Coming Soon products is a worthwhile enhancement. @amdrew

**Comment by amdrew** [comment]
@SDavisMedia I agree, can't see any reason why it shouldn't show

**Comment by amdrew** [comment]
@SDavisMedia Weird, this seems to work fine for me, maybe EDD changed something again? Could you give it a quick test on your end? Where do you not see the votes for a free download?

<img width="296" alt="screenshot 2017-09-15 23 03 49" src="https://user-images.githubusercontent.com/52581/30479625-31a9726a-9a6a-11e7-9a4a-a97b1c55a5b5.png">
<img width="480" alt="screenshot 2017-09-15 23 03 38" src="https://user-images.githubusercontent.com/52581/30479626-31abfd64-9a6a-11e7-998f-6a8f19f89457.png">
<img width="741" alt="screenshot 2017-09-15 23 03 21" src="https://user-images.githubusercontent.com/52581/30479627-31ac5d40-9a6a-11e7-826d-160e558de47a.png">

**Comment by amdrew** [comment]
@SDavisMedia I think I see the issue. I was using Twenty Sixteen and the voting somehow doesn't show for free or paid products on the single download page. They also don't show for Vendd. With Themedd, it shows the voting for a paid download, but not free. Is that what you saw?

I'll figure out why and get the vote counts showing for all themes.

**Comment by SDavisMedia** [comment]
@amdrew Yup!

**Comment by amdrew** [comment]
According to the code, the actual vote count isn't supposed to show at all on the front-end. The reason why it shows on Themedd (accidentally) is because there's a function in the plugin that should only run in the admin, to add the vote count to the pricing column. Since there's no `is_admin()` check in the function, it gets outputted into Themedd's sidebar due to the way pricing is handled.

I'm in the process of refactoring the code and putting everything inside a class like all our other plugins (this was one of my first!), and I'll place the admin function that is running inside an `is_admin()` check which will fix this issue.

But should vote counts be shown on the front-end? That's an interesting idea actually. If they are going to show at all, it would have to be above or below the "Coming Soon" message that is outputted at the bottom of the single download page. Coming Soon removes EDD's default purchase button and replaces it with the message. On theme's like Vendd and Themedd, we could add custom support to show this vote count in the sidebar for example.

**Comment by SDavisMedia** [comment]
@amdrew I personally thought the vote count being shown on the front-end was weird. But I went to necessary lengths to make it look someone logical: https://github.com/easydigitaldownloads/vendd/issues/236

Do whatever you think makes the most sense and I'll gladly make adjustments from there.

**Comment by amdrew** [comment]
@SDavisMedia 👍 It's been nuked in the latest master, going to do a bit more testing to make sure everything looks fine across themes. 

If we get any support tickets we can add it back as a "Show vote counts on front-end" admin option or similar.

**Comment by amdrew** [comment]
Closing, all looks good in 2016, Vendd, 2017 and themedd
