### ISSUE TITLE
Add Danish translations

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-coming-soon#20]
Incoming PR with community contributed translation files.

**Comment by cklosowski** [comment]
@brashrebel Since this is distributed on WordPress.org, we don't upload translation files into it anymore. They would contribute language files here: 
https://translate.wordpress.org/projects/wp-plugins/edd-coming-soon

Which it appears they already have.
<img width="977" alt="screen shot 2018-03-19 at 11 58 20 am" src="https://user-images.githubusercontent.com/1390124/37616370-e399fb46-2b6c-11e8-94a4-40a02e9c466a.png">

To use the Danish translation, they would simply change their site to Danish. With the new .org translation process, the files no longer need to be included in our release.

**Comment by brashrebel** [comment]
@cklosowski yeah, I figured that out _after_ opening issues and PRs on several of our repos. My bad. They can be disregarded. The contributor has been guided to the w.org translation system.

**Comment by cklosowski** [comment]
:+1:

**Comment by cklosowski** [comment]
Closing so as this has been taken care of on the .org translation system.
